var rule = {
    title:'Madouclub',
    host:'https://madou.club',
	homeUrl:'/category/fyclass',
	searchUrl:'/?s=**',
    url:'/category/fyclass/page/fypage',
    headers:{
       "User-Agent":"MOBILE_UA"
    },
    timeout:5000,
    class_name:'麻豆传媒&麻豆番外篇&麻豆花絮&hongkongdoll&psychoporntw&果冻传媒&天美传媒&皇家华人&兔子先生',//静态分类名称拼接
    class_url:'麻豆传媒&麻豆番外篇&麻豆花絮&hongkongdoll&psychoporntw&果冻传媒&天美传媒&皇家华人&兔子先生',//静态分类标识拼接
    limit:5,
    play_parse:true,
    lazy:'',
    一级:'.excerpts-wrapper&&article;h2&&Text;img&&data-src;.absolute.bottom-1&&Text;a&&href',
    二级:'*',
	搜索:'.excerpts-wrapper&&article;h2&&Text;img&&data-src;.absolute.bottom-1&&Text;a&&href',
	searchable:1,//是否启用全局搜索,
    quickSearch:1,//是否启用快速搜索,
    filterable:0,//是否启用分类筛选,
}
